#!/bin/sh

# dependencies
require dunstify || exit 1

value="$(cat /sys/class/power_supply/BAT0/capacity)"
status="$(cat /sys/class/power_supply/BAT0/status)"

danger="$(expr $value \<= 10)"
level="$(expr $value / 25)"

case "$level" in
	0)
		icon="\uf243"
		;;
	1)
		icon="\uf242"
		;;
	2)
		icon="\uf241"
		;;
	3)
		icon="\uf240"
		;;
	4)
		icon="\uf240"
		;;
esac

# send notification on danger
[ $danger = 1 ] && [ "$status" = "Discharging" ] && {
	dunstify --replace=23 -u CRITICAL "⚠️ Battery is low" "Plug me to the f-ing wall you moron I'm dying";
	icon="\uf244 \uf12a";
} || dunstify --close=23

[ "$status" = "Charging" ] && icon="$icon \uf0e7"

env printf "$icon $value%%"
