#!/bin/sh

# dependencies
require pacmd || exit 1

sink=$(pacmd list-sinks | grep -A 15 '* index')

value="$(echo "${sink}" | awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g')"

mute="$(echo "${sink}" | awk '/muted:/{ print $2 }')"

[ "$mute" = "yes" ] && icon="[M] "

echo "$icon$value%"
