#!/bin/sh

# dependencies
require iwctl || exit 1

state=$(iwctl station wlan0 show | grep State | awk '{ printf $2 }')

[ $state = "connected" ] && network="$(iwctl station wlan0 show | grep network | awk '{$1=$2=""; print}' | xargs)" || network="disconnected"

echo "$network"

