#!/bin/sh

APPLY_SCRIPT='apply'
BACKUP_SCRIPT='backup'

files="$(find -type f \
	| grep -v "^\./$APPLY_SCRIPT$" \
	| grep -v "^\./$BACKUP_SCRIPT$" \
	| sed 's|^\./||g')"

dirs=$(find -type d \
	| sed 's|^\./||g' \
	| grep -v '\.$')

# make all directories as necessary
toCreate=$(printf "$dirs" \
	| sed "s|^|mkdir -p $HOME/|g; s|$| \&|g")
printf "$toCreate" | sh

# copy all files
for f in $files
do
	cp $f $HOME/$f
done
