#!/bin/sh

selected="$(cut -d ';' -f1 ~/.local/assets/emoji | dmenu -g 3 -fn "$SL_FONT" -i -l 5 | sed 's/ .*//')"

[ -z "$selected" ] && exit

printf "$selected" | wl-copy
notify-send "$selected copied to clipboard."
