#!/bin/sh

# dependencies
require xbacklight dunstify sb || exit 1

delta=${2:-5}

[ "$1" = "up" ] && xbacklight -inc $delta &
[ "$1" = "down" ] && xbacklight -dec $delta &

dunstify --replace=85 -t 500 -h int:value:$(sb brightness -v) "🔆 brightness"
