#!/bin/sh

# dependencies
require xrandr || exit 1

internal=eDP1
external1=DP1
external2=HDMI1

connected1=$(xrandr | grep "$external1 disconnected")
connected2=$(xrandr | grep "$external2 disconnected")

# workstation mode
[ "$connected1" = '' ] && [ "$connected2" = '' ] && both='yes'

[ "$both" = 'yes' ] && arandr-layout.sh && exit

[ "$both" = '' ] && xrandr --output $external1 --off && xrandr --output $external2 --off
