#!/bin/sh

# dependencies
require xrandr || exit 1

internal=eDP1
external=HDMI1

connected=$(xrandr | grep "$external disconnected")

[ "$connected" = "" ] && xrandr --output "$internal" --off --output "$external" --auto || xrandr --output "$external" --off --output "$internal" --auto

~/.screenlayout/home.sh
