#!/bin/sh

# dependencies
require mpv sxiv zathura alacritty xdg-open || exit 1

mime="$(file --mime-type -b $1)"
case $mime in
	audio/*)
		mpv --no-video "$1"
	;;

	video/*)
		mpv "$1"
    ;;

	image/*)
		sxiv "$1"
	;;
	
	application/pdf)
       	zathura "$1"
    ;;

	text/*|application/json)
		nvim "$1"
	;;

	application/x-pie-executable)
		gdb "$1"
	;;

	application/x*)
		exit;
	;;

	# all other files
	*)
		notify-send "opening $mime file...\n"
		xdg-open "$1"
	;;
esac
