#!/bin/sh

# dependencies
require ffmpeg || exit 1

printf "🎹 Album Title: "
read album

printf "🎨 Artist: "
read artist

printf "📅 Year of Publication: "
read year

for file in "$@"
do
	cleanfile=$(basename "$file")
	noext=${cleanfile%.*}
	track=${noext%%:*}
	name=${noext#*:}
	echo "🎵 $artist - $name ($track)"
	ffmpeg -i "file:$file" -acodec copy \
		-metadata title="$name" \
		-metadata artist="$artist" \
		-metadata date="$year" \
		-metadata album="$album" \
		-metadata track="$track" \
		"$artist - $name.opus"
done
