#!/bin/sh

choice="$(printf 'lock\nshutdown\nreboot\nsuspend\n' | dmenu)"

[ "$choice" = "lock" ] && { slock & systemctl suspend ; }
[ "$choice" = "shutdown" ] && systemctl poweroff
[ "$choice" = "reboot" ] && systemctl reboot
[ "$choice" = "suspend" ] && systemctl suspend
