#!/bin/sh

choice="$(printf 'cancel\nshutdown\nreboot\nsuspend\n' | dmenu)"

[ "$choice" = "shutdown" ] && systemctl poweroff
[ "$choice" = "reboot" ] && systemctl reboot
[ "$choice" = "suspend" ] && systemctl suspend
