#!/bin/sh

notID=65

name='Elan Touchpad'
trackpad=$(xinput --list | grep "$name" | cut -f 2 | cut -d'=' -f 2)
prop='libinput Disable While Typing Enabled'
isBlocked=$(xinput list-props $trackpad | grep "$prop (" | cut -f 3)

[ "$isBlocked" = '0' ] && {
	xinput set-prop $trackpad "$prop" 1 ;
	dunstify --replace=$notID "🔒 trackpad locked" ;
} || {
	xinput set-prop $trackpad "$prop" 0 ;
	dunstify --replace=$notID "🔓 trackpad unlocked" ;
}
