#!/bin/sh

# dependencies
require pactl dwmblocks sb || exit 1

# Sink ID
sink=0

# interval
delta=${2:-5}

# speaker volume
[ "$1" = "up" ] && echo $delta | xargs -I{} pactl set-sink-volume $sink +{}%
[ "$1" = "down" ] && echo $delta | xargs -I{} pactl set-sink-volume $sink -{}%

# speaker mute
[ "$1" = "mute" ] && pactl set-sink-mute $sink toggle

# set volume level
[ "$1" = "set" ] && pactl set-sink-volume "$sink" $2%

level="$(sb volume -v)"
mute="$(sb volume -m)"

icon="🔇"
[ "$mute" = "no" ] && icon="🔉"
dunstify --replace=85 -t 500 -h int:value:$level "$icon volume"

# update dwm volume block
kill -44 $(pidof dwmblocks)
