#!/bin/sh

files="$(grep -r --exclude-dir='.git' "$1")"

[ "$2" = "" ] && printf "%s\n" "$files" && exit

found="$(printf "%s" "$files" | cut -d ':' -f 1)"
printf "%s" "$found" | xargs sed -i "s/$1/$2/g"
