#!/bin/sh

mime="$(file --mime-type -b $1)"
case $mime in
	audio/*)
		mpv --no-video "$1"
	;;

	video/*)
		mpv "$1"
    ;;

	image/svg*)
		inkscape "$1"
	;;

	image/*)
		sxiv "$1"
	;;
	
	application/pdf)
       	zathura "$1"
    ;;

	text/*|application/json)
		$EDITOR "$1"
	;;

	application/zip)
		$EDITOR "$1"
	;;

	application/x-pie-executable)
		gdb "$1"
	;;

	application/*|inode/*)
		exit;
	;;

	# all other files
	*)
		notify-send "opening $mime file...\n"
		xdg-open "$1"
	;;
esac
