#!/bin/sh

takeScreen() {
	grim -g "$(slurp -w 0)" - | tee ~/pics/screenshot.png | wl-copy && notify-send "📷 Picture saved!"
}

takeWholeScreen() {
	slurp &
	sleep 0.2
	kill $!
	grim - | tee ~/pics/screenshot.png | wl-copy && notify-send "📷 Picture saved!"
}

[ "$1" = "-f" ] && takeWholeScreen && exit

takeScreen
