#!/bin/sh

# interval
delta=${2:-5}

# speaker volume
[ "$1" = "up" ] && echo $delta | xargs -I{} pamixer -i {}
[ "$1" = "down" ] && echo $delta | xargs -I{} pamixer -d {}

# speaker mute
[ "$1" = "mute" ] && pamixer -t

# set volume level
[ "$1" = "set" ] && pactl --set-volume $2%

level="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"

icon="🔇"
[ "$mute" = "false" ] && icon="🔉"
dunstify --replace=85 -t 500 -h int:value:$level "$icon volume"
