#!/bin/sh

file=$(readlink -f "$1")

directory=${file%/*}
filename=${file%.*}
filext=${file##*.}

case "$filext" in
	c) cc "$file" -o "$filename" ;;
	cpp) g++ "$file" -o "$filename" ;;
	go) go build ;;
	h) sudo make install && make clean ;;
	ms) groff -Kutf8 -ms "$file" -Tpdf > "$filename".pdf ;;
esac
