#!/bin/sh

files="$(cat ./Dotfiles)"

backup() {
	echo "Backup $1..."
	mkdir -p backup
	cp -r ~/$1 backup/$1
}

revert() {
	echo "Revert $1..."
	mv backup/$1 ~/$1
	rmdir backup > /dev/null 2>&1
}

apply() {
	echo "Moving $1..."
	rm -rf ~/$1
	cp -r $(pwd)/$1 ~
}

[ $1 = "backup" ] && process=backup
[ $1 = "revert" ] && process=revert
[ $1 = "apply" ] && process=apply

for file in $files
do
	$process $file
done
