#!/bin/sh

selected="$(cut -d ';' -f1 ~/.local/assets/emoji | dmenu -i -l 10 | sed 's/ .*//')"

[ -z "$selected" ] && exit

printf "$selected" | xclip -sel clip
notify-send "$selected copied to clipboard."
