#!/bin/sh

# dependencies
require dmenu xclip || exit 1

selected="$(cut -d ';' -f1 ~/.local/assets/emoji | dmenu -fn "$SL_FONT" -i -l 10 | sed 's/ .*//')"

[ -z "$selected" ] && exit

printf "$selected" | xclip -sel clip
notify-send "$selected copied to clipboard."
