#!/bin/sh

# dependencies
require light dwmblocks || exit 1

delta=${2:-5}

[ $1 = "up" ] && light -A $delta
[ $1 = "down" ] && light -U $delta

# update dwm brightness block
kill -45 $(pidof dwmblocks)
