#!/bin/sh

# dependencies
require mpc dunstify || exit 1

nid=30
delta=${2:-5}

[ "$1" = "up" ] && mpc volume +$delta && dunstify --replace=$nid "🎵 $(mpc volume)"
[ "$1" = "down" ] && mpc volume -$delta && dunstify --replace=$nid "🎵 $(mpc volume)"
