#!/bin/sh

printf "🎹 Album Title: "
read album

printf "🎨 Artist: "
read artist

printf "📅 Year of Publication: "
read year

for file in "$@"
do
	noext=${file%.*}
	track=${noext%%:*}
	name=${noext#*:}
	echo "🎵 $artist - $name ($track)"
	#opusenc --artist "$artist" \
	#	--title "$name" \
	#	--album "$album" \
	#	--date "$year" \
	#	"$file" "$artist - $file"
	ffmpeg -i "file:$file" -acodec copy \
		-metadata title="$name" \
		-metadata artist="$artist" \
		-metadata date="$year" \
		-metadata album="$album" \
		-metadata track="$track" \
		"$artist - $name.opus"
done
