#!/bin/sh

# dependencies
require scrot slop || exit 1

takeScreen() {
	scrot $@ -o ~/pics/screenshot.png && notify-send "📷 Picture saved!"
	xclip -sel clip -t image/png < ~/pics/screenshot.png
}

[ "$1" = "-f" ] && takeScreen && exit

sel="$(slop -c 0.9,0.9,0.9,0.8 -f '%x,%y,%w,%h')"

[ "$sel" = "" ] && exit

takeScreen -a $sel
