#!/bin/sh

[ "$1" = "-f" ] && scrot -o ~/pics/screenshot.png && notify-send "📷 Picture saved!" && exit

sel="$(slop -c 0.9,0.9,0.9,0.8 -f '%x,%y,%w,%h')"

[ "$sel" = "" ] && exit

scrot -a $sel -o ~/pics/screenshot.png && notify-send "📷 Picture saved!"
