#!/bin/sh

# script that uses pactl to set and get the current volume

# Sink ID
sink=0

# interval
delta=${2:-5}

# speaker volume
[ $1 = "up" ] && echo $delta | xargs -I{} pactl set-sink-volume $sink +{}%
[ $1 = "down" ] && echo $delta | xargs -I{} pactl set-sink-volume $sink -{}%

# speaker mute
[ $1 = "mute" ] && pactl set-sink-mute $sink toggle

# set volume level
[ $1 = "set" ] && pactl set-sink-volume "$sink" $2%

# update dwm volume block
kill -44 $(pidof dwmblocks)
