#!/bin/sh

# dependencies
require dunstify || exit 1

value="$(cat /sys/class/power_supply/BAT0/capacity)"
status="$(cat /sys/class/power_supply/BAT0/status)"

danger="$(expr $value \<= 10)"

# send notification on danger
[ $danger = 1 ] && [ "$status" = "Discharging" ] && {
	dunstify --replace=23 -u CRITICAL "⚠️ Battery is low" "Plug me to the f-ing wall you moron";
	icon="! ";
} || dunstify --close=23

[ "$1" = "" ] && {
	[ "$status" = "Charging" ] && icon="[C] "
	exec printf "$icon$value%%"
}
[ "$1" = "-v" ] && exec echo $value
[ "$1" = "-c" ] && [ "$status" = "Charging" ] && exec echo "yes" || exec echo "no"
