#!/bin/sh

# dependencies
require pactl || exit 1

sink="$(pactl get-default-sink)"

value="$(echo "$(pactl get-sink-volume $sink)" | awk '{ print $5 }' | sed 's/[%|,]//g')"
mute="$(echo "$(pactl get-sink-mute $sink)" | awk '/Mute: /{ print $2 }')"

[ "$1" = "-m" ] && exec echo $mute
[ "$1" = "-v" ] && exec echo $value

[ "$mute" = "yes" ] && icon="[M] "
echo "$icon$value%"
